
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    environment:
      - CONFIG_PATH=/app/config.yml
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

volumes:
  mongo-data:
